/**
 * Self-contained plain-JS copy of the pure Sentry helpers for raw-Node
 * contexts (`vite.config.ts`, `scripts/*`). Generated by hand from
 * `./index.ts` — keep in sync (same function names + semantics, zero
 * TypeScript syntax). `server.test.ts` does NOT cover this file; the
 * canonical tests target `./index.ts`.
 */

export function defaultTracesSampleRate(environment) {
	return environment === 'production' ? 0.1 : 1.0
}

export function readSentryEnv(raw) {
	const dsn = raw.SENTRY_DSN?.trim() || raw.PUBLIC_SENTRY_DSN?.trim() || ''
	const vercelEnv = raw.VERCEL_ENV?.trim()
	const environment =
		raw.SENTRY_ENVIRONMENT?.trim() ||
		(vercelEnv === 'production' ? 'production' : (vercelEnv ?? '')) ||
		'development'
	const release = raw.SENTRY_RELEASE?.trim() || raw.VERCEL_GIT_COMMIT_SHA?.trim() || 'dev'
	const parsed = Number(raw.SENTRY_TRACES_SAMPLE_RATE)
	return {
		dsn,
		environment,
		release,
		tracesSampleRate: Number.isFinite(parsed) ? parsed : defaultTracesSampleRate(environment),
	}
}

export function shouldInitSentry(dsn, opts) {
	if (!dsn || !dsn.trim()) return false
	const mode = opts?.mode ?? (typeof process !== 'undefined' ? process.env.MODE : undefined)
	if (mode === 'test') return false
	if (
		opts?.mode === undefined &&
		typeof process !== 'undefined' &&
		(process.env.VITEST || process.env.PLAYWRIGHT_TEST)
	) {
		return false
	}
	const hostname = opts?.hostname?.toLowerCase()
	if (hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '::1') return false
	const url = opts?.url?.toLowerCase()
	if (url?.startsWith('http://localhost') || url?.startsWith('http://127.0.0.1')) return false
	return true
}

const SENSITIVE_HEADERS = new Set(['cookie', 'authorization', 'x-alfred-secret'])

const SENSITIVE_KEYS = new Set([
	'salt',
	'private_salt_hash',
	'alfred_webhook_secret',
	'alfred_stream_secret',
	'openrouter_api_key',
	'serper_api_key',
	'resend_api_key',
	'vapid_private_key',
	'auth_secret',
])

export const SENTRY_PREVIEW_CHARS = 500

function truncate(value) {
	if (typeof value === 'string' && value.length > SENTRY_PREVIEW_CHARS) {
		return `${value.slice(0, SENTRY_PREVIEW_CHARS)}…[truncated]`
	}
	return value
}

function scrubValue(key, value) {
	const lower = key.toLowerCase()
	if (SENSITIVE_KEYS.has(lower) || lower.includes('secret') || lower.includes('api_key')) {
		return '[Redacted]'
	}
	if (lower === 'cookie' || lower === 'authorization' || lower === 'x-alfred-secret') {
		return '[Redacted]'
	}
	return truncate(value)
}

function scrubRecord(record) {
	const out = Array.isArray(record) ? [...record] : {}
	for (const [key, value] of Object.entries(record)) {
		out[key] = scrubAny(key, value)
	}
	return out
}

function scrubAny(key, value) {
	if (value !== null && typeof value === 'object') {
		if (Array.isArray(value)) return value.map((v) => scrubAny(key, v))
		return scrubRecord(value)
	}
	return scrubValue(key, value)
}

export function scrubEvent(event) {
	const headers = event.request?.headers
	if (headers) {
		for (const name of Object.keys(headers)) {
			if (SENSITIVE_HEADERS.has(name.toLowerCase())) headers[name] = '[Redacted]'
		}
	}
	const qs = event.request?.query_string
	if (typeof qs === 'string' && qs) {
		try {
			const params = new URLSearchParams(qs)
			if (params.has('salt')) {
				params.set('salt', '[Redacted]')
				if (event.request) event.request.query_string = params.toString()
			}
		} catch {
			// Non-URL query strings pass through untouched.
		}
	}
	if (event.request?.cookies) {
		for (const name of Object.keys(event.request.cookies)) {
			event.request.cookies[name] = '[Redacted]'
		}
	}
	if (event.request?.data !== undefined && event.request?.data !== null) {
		if (event.request && typeof event.request.data === 'object') {
			event.request.data = scrubRecord(event.request.data)
		} else if (event.request) {
			event.request.data = truncate(event.request.data)
		}
	}
	if (event.contexts) {
		for (const [name, ctx] of Object.entries(event.contexts)) {
			if (ctx && typeof ctx === 'object') event.contexts[name] = scrubRecord(ctx)
		}
	}
	if (event.extra) event.extra = scrubRecord(event.extra)
	if (event.breadcrumbs) {
		for (const crumb of event.breadcrumbs) {
			if (crumb?.data) crumb.data = scrubRecord(crumb.data)
		}
	}
	return event
}

export function buildSentryOptions(input) {
	const environment = input.environment?.trim() || 'development'
	const traces =
		typeof input.tracesSampleRate === 'string'
			? Number(input.tracesSampleRate)
			: (input.tracesSampleRate ?? Number.NaN)
	return {
		dsn: input.dsn?.trim() ?? '',
		environment,
		release: input.release?.trim() || 'dev',
		tracesSampleRate: Number.isFinite(traces) ? traces : defaultTracesSampleRate(environment),
		replaysSessionSampleRate: 0,
		sendDefaultPii: false,
		debug: input.debug ?? false,
		beforeSend: (event) => scrubEvent(event),
	}
}
