export {
	BODACC_API_URL,
	buildBodaccUrl,
	fetchBodaccLeads,
	getActe,
	getCompanyName,
	getDepot,
	getEtablissements,
	getJugement,
	getPersonnes,
	getSiren,
	parseJsonField,
	runExample,
} from './client.js'
export type {
	BodaccActe,
	BodaccApiResponse,
	BodaccCategory,
	BodaccDepot,
	BodaccEtablissement,
	BodaccFamilyCode,
	BodaccImmatriculation,
	BodaccJugement,
	BodaccPersonne,
	BodaccPersonneMorale,
	BodaccPersonnePhysique,
	BodaccQueryOptions,
	BodaccRecord,
} from './types.js'
export type { FetchFn as BodaccFetchFn } from './client.js'
