export { aosom, aosomSearchUrl, createAosomAdapter } from './aosom/index.js'
export type { EmagLocale } from './emag/index.js'
export { createEmagAdapter, emag, emagSearchUrl } from './emag/index.js'
export { createSuprevaAdapter, supreva, suprevaSearchUrl } from './supreva/index.js'
export * from './types.js'
